- Created DAO, Service, Injector and Storage
NikolayFatkullin/Shop pull request #1
Opened 2021-01-11 16:11 UTC by NikolayFatkullin

2021-01-11 17:09 UTC, AndreiYazadzhi approved these changes
I`m aprove this but correct comment)

2021-01-11 17:09 UTC, AndreiYazadzhi commented on src/main/java/com/shop/model/Car.java
> +        this.id = id;
Do yo need id in constructor?

2021-01-11 18:10 UTC, NikolayFatkullin commented on src/main/java/com/shop/model/Car.java
> +        this.id = id;
Oh, Thank you, didn't see that =)

2021-01-12 08:52 UTC, Sofasmile requested changes

2021-01-12 08:52 UTC, Sofasmile commented on src/main/java/com/shop/model/Car.java
> +    public Car(String model, Manufacturer manufacturer, List<Driver> drivers) {
https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/03_dao_service_checklist.html
last point

2021-01-12 08:52 UTC, Sofasmile commented on src/main/java/com/shop/service/impl/ManufacturerServiceImpl.java
> +    ManufacturerDao manufacturerDao;
how about access modifier?

2021-01-12 08:52 UTC, Sofasmile commented on src/main/java/com/shop/service/impl/ManufacturerServiceImpl.java
> +        return manufacturer;
```suggestion
        return manufacturerDao.create(manufacturer);
```

2021-01-12 08:52 UTC, Sofasmile commented on src/main/java/com/shop/service/impl/ManufacturerServiceImpl.java
> +        return manufacturer;
```suggestion
        return manufacturerDao.update(manufacturer);
```

2021-01-12 09:24 UTC, Sofasmile approved these changes

2021-01-12 09:24 UTC, Sofasmile commented on src/main/java/com/shop/model/Car.java
> +        this.drivers = new ArrayList<>();
```suggestion
        drivers = new ArrayList<>();
```

2021-01-12 16:06 UTC, merged