- All application works with MySQL, old Storage removed
NikolayFatkullin/Shop pull request #4
Opened 2021-01-17 05:45 UTC by NikolayFatkullin

2021-01-18 07:54 UTC, Fedich09 approved these changes

2021-01-18 07:54 UTC, Fedich09 commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +                if (driver.getId() != null) {
```suggestion
                if (driver.getId() != null) {
```
why do we need this check?

2021-01-18 08:05 UTC, NikolayFatkullin commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +                if (driver.getId() != null) {
method getDriver(), can return Driver object with null fields =)

2021-01-18 11:55 UTC, dmytro-hryhoruk requested changes

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +                Driver driver = getDriver(resultSet);
let's store this in a local variable instead of calling it twice

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +                if (driver.getId() != null) {
@NikolayFatkullin Could you describe such case?

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +            resultSet.relative(-1);
why not previous()?

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +    private List<Driver> getDrivers(ResultSet resultSet, Long id) {
```suggestion
    private List<Driver> getDrivers(ResultSet resultSet, Long carId) {
```

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/DriverDaoJdbcImpl.java
> +        String deleteConnections = "DELETE FROM cars_drivers WHERE driver_id = ?";
let's not delete references from cars_drivers

2021-01-18 11:55 UTC, dmytro-hryhoruk commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +        String deleteConnections = "DELETE FROM cars_drivers WHERE car_id = ?";
let's not delete references from cars_drivers

2021-01-18 12:15 UTC, NikolayFatkullin commented on src/main/java/com/shop/dao/impl/CarDaoJdbcImpl.java
> +            resultSet.relative(-1);
1. In method getAll, I used Left Join, so DB can return fields where drivers have null because in those cars we don't have any connections with drivers table.
2. I didn't know about previous. This method I've found on google and didn't look for another method

2021-01-19 13:28 UTC, dmytro-hryhoruk approved these changes

2021-01-19 14:17 UTC, merged