Version 6.0 is ready
NikolayFatkullin/Shop pull request #6
Opened 2021-01-20 14:29 UTC by NikolayFatkullin

- From this version, you can create new Drivers, Cars, and Manufacturers from your Browser. It was difficult, but we do everything for our dear customers.
- We also have added the function of delete Cars, Drivers, and Manufacturers from your browser (but only if you admin), have fun =)
- And in the end, we have added a function to see all Drivers, Cars or Manufacturers, in your web browser.

2021-01-20 15:41 UTC, IvanLuchkin requested changes

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/AllCarsController.java
> +public class AllCarsController extends HttpServlet {
We should use verbs in the names of our classes since they are responsible for some specific action

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/AllCarsController.java
> +        List<Car> carList = carService.getAll();
```suggestion
        List<Car> cars = carService.getAll();
```

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/AllCarsController.java
> +        req.getRequestDispatcher("/WEB-INF/views/cars/all.jsp").forward(req, resp);
I would rename all .jsp files into specific ones, for example `all-cars.jsp` and `create-car.jsp`. Yes, they are separated into different folders, but there is always a chance of confusion because of the same file names

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/CreateCarController.java
> +        carService.create(car);
We can remove the `car` variable and create this object inside the parentheses

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/CreateCarController.java
> +        resp.sendRedirect(req.getContextPath() + "all");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/all");
```
Maybe this option is more correct? I'm not sure though

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/cars/drivers/AddDriverToCarController.java
> +        carService.addDriverToCar(driver, car);
We could write this in a single line, but it's up to you

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/drivers/AllDriversController.java
> +        List<Driver> driverList = driverService.getAll();
```suggestion
        List<Driver> drivers = driverService.getAll();
```

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/manufacturers/AllManufacturerController.java
> +public class AllManufacturerController extends HttpServlet {
```suggestion
public class GetAllManufacturersController extends HttpServlet {
```

2021-01-20 15:41 UTC, IvanLuchkin commented on src/main/webapp/WEB-INF/views/cars/drivers/add.jsp
> +--%>
Auto-generated comments should be removed

2021-01-20 16:18 UTC, IvanLuchkin approved these changes

2021-01-20 16:18 UTC, IvanLuchkin commented on src/main/java/com/shop/controller/drivers/GetAllDriversController.java
> +        req.getRequestDispatcher("/WEB-INF/views/drivers/all-drivers.jsp").forward(req, resp);
We were told not to use plurals in package names
```suggestion
        req.getRequestDispatcher("/WEB-INF/views/driver/all-drivers.jsp").forward(req, resp);
```

2021-01-21 12:00 UTC, dmytro-hryhoruk requested changes

2021-01-21 12:00 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/</url-pattern>
check https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/08_servlets_practice_checklist.html about urls naming

2021-01-21 17:23 UTC, dmytro-hryhoruk approved these changes

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/delete</url-pattern>
```suggestion
        <url-pattern>/cars/delete</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/delete</url-pattern>
```suggestion
        <url-pattern>/drivers/delete</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/all</url-pattern>
```suggestion
        <url-pattern>/cars</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/all</url-pattern>
```suggestion
        <url-pattern>/manufacturers</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/driver/add</url-pattern>
```suggestion
        <url-pattern>/cars/drivers/add</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/car/create</url-pattern>
```suggestion
        <url-pattern>/cars/create</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/create</url-pattern>
```suggestion
        <url-pattern>/drivers/create</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/create</url-pattern>
```suggestion
        <url-pattern>/manufacturers/create</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/all</url-pattern>
```suggestion
        <url-pattern>/drivers</url-pattern>
```

2021-01-21 17:23 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/manufacturer/delete</url-pattern>
```suggestion
        <url-pattern>/manufacturers/delete</url-pattern>
```

2021-01-22 10:19 UTC, merged